### ISSUE TITLE
Duplication Issue (1.0.16)

### ISSUE THREAD

**Issue by sonictx03** [Lupicus/ClaimChunk#10]
You can duplicate placeable items (blocks) with this mod. How to replicate is as follows: 

It requires two players, the owner of the claim block and the duplicator. The owner places a claim block and gives permission to open storages (chests) but not place blocks. The duplicator will then place a block. It'll break and drop the block, but the duplicator will still have it in their inventory, duplicating it. Unknown if a mod compatibility issue causes this or not, as I am unable to test it on my own, but the problem has occurred in modpacks.

**Comment by Lupicus** [comment]
What version of Minecraft are you using? It shouldn't drop blocks as I'm canceling place event which Forge removes it and normally bypasses any drop logic. Does it happen with cobblestone or dirt blocks?

**Comment by Lupicus** [comment]
If you can give me a modpack that has this issue then I can test it.

**Comment by sonictx03** [comment]
The modpack was Dawncraft (version 1.6_hf). I think it was a mod incompatibility issue, as it happened when someone was trying to place enchanted books. I don't know which mod it was (I think apotheosis?). I didn't do any testing as I quickly had to remedy the issue and made the claim blocks unavailable.

**Comment by Lupicus** [comment]
The issue is with Supplementaries mod.

**Comment by Lupicus** [comment]
One solution for books is to turn that feature off in config/supplementaries-common, section tweaks.placeable_books with enabled = false

**Comment by Lupicus** [comment]
version 1.0.17 should fix this issue
