### ISSUE TITLE
Adding players

### ISSUE THREAD

**Issue by captcookie** [Lupicus/ClaimChunk#11]
I think I am not typing the (*) correctly to add player permissions to modify. For example, I add their name in both the top and bottom and add <name>*. Even without the star, players are not able to open chest or interact with button and etc. I will keep trying. Both of us are opped, but when I deop the other they have no access when they should.

**Comment by captcookie** [comment]
![image](https://github.com/Lupicus/ClaimChunk/assets/19790335/b7d285c2-c983-49a0-8c78-d97135870500)

This worked! Is this how it is supposed to be? And does this allow anyone to modify? or just me and lalasofi?

**Comment by captcookie** [comment]
I can confirm without the * she cannot open chest or use buttons or doors on the property. So, I am not sure what the point of modify is when * is not used. I am sure I just do not understand. 

What I want to accomplish is have people added with limited access. e.g. open doors but not modify blocks.

**Comment by Lupicus** [comment]
You have to type the names exactly (using capitals). It would be rare to add * in the Modify field as that gives anyone the ability to change that chunk except claiming that chunk. More common to add * to Access field for a map with a village/city.
To give people limited access is to put * in the Access field.
If you want your friend to be able to modify blocks and access stuff then you put their exact name in the Modify field.

**Comment by Lupicus** [comment]
Also note that you don't need to put your name in those fields if that chunk is owned by you.

**Comment by captcookie** [comment]
Please close this I figured out that the world spawn was breaking it. Now that world spawn isnt there everything is working better and yes the names were wrong too.

**Comment by Lupicus** [comment]
Glad you got it working.
