### ISSUE TITLE
Allying

### ISSUE THREAD

**Issue by celsiusqc** [Lupicus/ClaimChunk#2]
Hi,
Could you please add support to add mods as allies so mods like Create and Industrial Forgoing can place blocks in claimed chunks?
Create deployers cannot be used currently because of this.
Thanks

**Comment by Lupicus** [comment]
I added modify list to claim block. You can put the fake players name in it. It isn't easy to determine them. It seems all ones from Industrial Forgoing use [IF]. The Create mod uses different ones, like Deployer and Plough.
