### ISSUE TITLE
[1.16.5] When this mod is installed, the bucket pickup liquid animation + sounds are completely gone.

### ISSUE THREAD

**Issue by Gbergz** [Lupicus/ClaimChunk#3]
When this mod is installed, the bucket pickup liquid animation + sounds are completely gone, possibly more stuff?

### Versions
**Minecraft:** 1.16.5
**Forge:** 36.1.61
**Chunk Claim:** 1.0.0.7

### Videos

**With ClaimChunk Installed:** (Sound and animation missing)
https://streamable.com/8daeq7

**Without ClaimChunk Installed:** (Works as expected)
https://streamable.com/0chv84

Hopefully this can be solved.
**-** Gbergz

**Comment by Lupicus** [comment]
Thanks for the report, should be fixed in latest version.

**Comment by Gbergz** [comment]
Sweet! Thank you.
