### ISSUE TITLE
Modular routers placed the claimed chunk block and now I cannot access the chunk

### ISSUE THREAD

**Issue by TrevNel** [Lupicus/ClaimChunk#9]
Accidently shift clicked the block into modular router and now I cannot do anything within the chunk.
Got the routers to break the block by managing them outside the chunk, and the chunk is still claimed

Playing on a server so I cannot use op permissions, I sent a request to the server mods, but I was wondering if there was any other way around this.

**Comment by Lupicus** [comment]
Please provide the full name for claim chunk and modular router mods.

**Comment by TrevNel** [comment]
I'm not sure what names you need, but the attached image shows how it shows up in game.

![2022-09-19_14 54 39](https://user-images.githubusercontent.com/8564673/191082309-a41c51fa-a274-4a54-9869-192650bd3483.png)

**Comment by Lupicus** [comment]
Inside the game instance folder is a mods folder, then paste the file name for Claim chunk and modular router mods, like:
ClaimChunk-1.18-1.0.0.14.jar
modular-routers-1.18.2-9.1.1-93.jar

**Comment by TrevNel** [comment]
ClaimChunk-1.16.2-1.0.0.10
modular-routers-1.16.5-7.4.0-55

There we go.

I'm trying to recreate this in a single player world so that I can try to find a way to solve my issue. But the router in the single player world will not place the claim chunk block, so this is interesting....

**Comment by Lupicus** [comment]
Is there a reason you are using old version of Claim Chunk for 1.16.4+ of Minecraft (determined by modular routers mod)?
I believe that the newer one for 1.16.3+ should not let a fake player place claim blocks resulting in this happening, but I would have to try it again to be sure.

**Comment by TrevNel** [comment]
I was just using the version that the modpack Vault Hunters supported. 
If I upgraded the client side should this fix my problem, or would I have to ask the mods to update the server side as well?

**Comment by Lupicus** [comment]
It would need to be on both sides, but they would still need to fix that existing chunk. I would have to duplicate it and then see what steps could fix it.

**Comment by Lupicus** [comment]
I'm thinking that they (operator) can issue /claims with the fake player uuid (in suggestion list) and remove option.

**Comment by TrevNel** [comment]
That would be nice. Just waiting until they respond then. Thank you.

**Comment by TrevNel** [comment]
The operators have resolved the issue. I may close this ticket as you mentioned updated versions limit the fake players being able to place claim blocks

**Comment by Lupicus** [comment]
It didn't place in single player world because your too close to spawn and it tries to that send message to the fake player.
You can either change the config or move spawn.
I tried the latest version on 1.16.5 and it blocks placing from the fake player.
